server:
  port: 8090
  
spring:
  application:
    name: Comment-api-query 
  profiles:
    active: local
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://localhost:3306/comment?characterEncoding=UTF-8&serverTimezone=UTC
    username: comment
    password: '!test1234'
  jpa:
    hibernate:
      ddl-auto: update